### ISSUE TITLE
API Rate Limit Issues

### ISSUE THREAD

**Issue by danielnolan** [jarthod/survey-gizmo-ruby#36] opened 2015-08-11 21:18 UTC
As of today, we are running into API rate limit issues when calling survey.questions. The survey this error is happening on has 8 pages. http://apihelp.surveygizmo.com/help/article/link/api-request-limits

**Comment by easyecho** [comment] 2015-08-11 23:53
According to SurveyGizmo "It appears on Sunday we had an issue with account abusing the API which caused a large problem for the application and our users as a whole. That is why this API limit was put in place today, to prevent something like that happening again."   The article in the above link was modified after it was posted and the limits were increased for each of the account types.

**Comment by apurvis** [comment] 2015-08-12 01:24
at lumos we use our own Pester gem to handle retries on exceptions.  it has options for linear backoff (try again in N seconds, then N more seconds, etc etc), exponential backoff (try again in 1 second, then 2, then 4, then 8, then 16, etc) and more.  

i was going to add a comment about it to the readme because it works well; we see a lot of timeouts and other strange exceptions from them.

https://github.com/lumoslabs/pester

**Comment by apurvis** [comment] 2015-08-12 01:24
(we use it for all external API calls to things with a bad habit of timing out or failing, like Amazon web services (cough))

**Comment by apurvis** [comment] 2015-08-12 07:06
e.g. 
```ruby
Pester.retry_with_exponential_backoff(logger: Logger.new(STDOUT), max_attempts: 15)
   # surveygizmo stuff here
end
```

**Comment by apurvis** [comment] 2015-08-12 07:25
If your .questions call is failing 100% of the time because of timeouts, your problem is probably sub question related.
See here:
https://github.com/RipTheJacker/survey-gizmo-ruby/blob/master/lib/survey_gizmo/resource.rb#L72-L74

and here:
https://github.com/RipTheJacker/survey-gizmo-ruby/blob/master/lib/survey_gizmo/api/question.rb#L38-L41

The SG API does not return sub questions!  It only gives you skus for them in the parent question.

So the current way to get sub_questions is to call the API one at a time for each subquestion.  There's no pause in between these API calls so a lot of questions + subquestions = a lot of API calls very quickly.

There's a few fixes you could try -
- get surveygizmo to fix this bug!  sub questions are questions too!  
- find a way to get more than one question by ID in a single API call.   i can't see a way based on what is documented but maybe something with filters...
- setup a configurable option for time to sleep between subquestion queries.

**Comment by jarthod** [comment] 2015-08-12 08:05
Indeed this kind of error is caused by SG and I don't think there's anything to be done in the gem, isn't it ?

**Comment by apurvis** [comment] 2015-08-12 08:06
well putting a sleep(60) in there between sub question retrievals would fix
it.  it would also make running scripts interminably slow.

but i think the best thing is for people to complain, and loudly.  they
have a bug or bad feature that is fine if we are allowed to make extra API
calls but now that they are rate limiting us it sucks.

**Comment by apurvis** [comment] 2015-08-17 19:12
i spoke to an SG representative who said they can manually increase the rate limit for API users who are not abusive.  He also said "I feel that we should have notified everyone before adding the rate limit and that the rate limit should have been high enough to allow for sequential calls from a single thread to be made without hitting that limit" so I think they understand the concerns.

**Comment by maxkwallace** [comment] 2015-10-14 15:07
I recently did an NPS survey for SurveyGizmo and mentioned API rate-limiting as an issue. One of their representatives responded to my comment and mentioned that they were currently doing a study on SurveyGizmo API usage.

So, if you have feedback or input on the API rate-limiting situation, now would be a great time to share it with the folks at SurveyGizmo! I already pointed them to this thread.

**Comment by maxkwallace** [comment] 2015-10-14 15:21
After testing this out, it seems like `survey-gizmo-ruby`, this Gem, simply returns `nil` if a request fails due to a timeout. This is definitely ambiguous... it's not clear at all why `nil` is being returned. A better API would be to throw an exception if something goes wrong with the request, including receiving a 429 back from the server.

**Comment by apurvis** [comment] 2015-10-16 12:13
@maxkwallace i feel like that is a separate issue but yes i have seen that behavior as well... i think that the `first` and `all` methods need to raise an exception instead of returning `nil` or `[]` when the response is not "ok":
https://github.com/RipTheJacker/survey-gizmo-ruby/blob/master/lib/survey_gizmo/resource.rb#L58-L91

feel free to submit a PR.

**Comment by apurvis** [comment] 2015-10-16 18:30
OK I submitted a PR: https://github.com/RipTheJacker/survey-gizmo-ruby/pull/39

**Comment by maxkwallace** [comment] 2015-10-16 18:42
@apurvis Awesome! This will be a huge help. My application exports SG data to other services intermittently, so having some guarantee of response integrity is really important (otherwise, data might be out of date for quite a while).

**Comment by apurvis** [comment] 2015-10-19 22:49
adrien just released 4.0.0 today with the change

**Comment by apurvis** [comment] 2015-12-23 02:37
FWIW I have a PR that would add a configurable sleep then retry on rate limit exceeded issues.
https://github.com/RipTheJacker/survey-gizmo-ruby/pull/48/files

**Comment by jarthod** [comment] 2015-12-24 09:47
This PR is now merged in master if you want to try it. It'll be released a bit later with 5.0

**Comment by jarthod** [comment] 2015-12-30 11:22
`5.0.2` now released

**Closed by jarthod** 2015-12-30 11:22 UTC

**Comment by apurvis** [comment] 2015-12-30 12:57
5.0.2 does 2 things that should solve this - 

1. it's way less chatty.  SG started returning info about sub objects with the responses so, for instance a Page contains its Questions (_and_ their Options), meaning 1 API request where there were formerly many
2. it has built in rate limit recovery

read the README for more info
